### ISSUE TITLE
Tagged release?

### ISSUE THREAD

**Issue by xthursdayx** [marc-sensenich/sn-nord-theme#4]
Hi, I'm trying to include this theme in the [Standard Notes self-hosted extension repo](https://github.com/iganeshk/standardnotes-extensions/), however it can only be processed if there is a release associated with the repo tags. Do you think you could make a release to go with the most recent tag? Cheers!

**Comment by marc-sensenich** [comment]
@xthursdayx I've manually created a r[elease for v0.0.18](https://github.com/marc-sensenich/sn-nord-theme/releases/tag/v0.1.8) and tested that it is processable by https://github.com/iganeshk/standardnotes-extensions/. I'm going to close this issue for now and the next time I update this codebase I'll add automatic releases to ensure it can be readily used in the future

**Comment by xthursdayx** [comment]
Great, thanks a lot!
